AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  covid-api-lambda

  Sample SAM Template for covid-api-lambda

Globals:
  Function:
    Timeout: 5

Resources:
  # Helpers layer
  ApiLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: api-layer
      Description: API Layer
      ContentUri: src/layer/
      CompatibleRuntimes:
        - nodejs16.x
      RetentionPolicy: Retain

  getHealth:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/
      Handler: get-health.getHealth
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        getAll:
          Type: Api
          Properties:
            Path: /getHealth
            Method: GET
  getAll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/
      Handler: get-all.getAll
      Runtime: nodejs16.x
      Layers:
        - !Ref ApiLayer
      Architectures:
        - x86_64
      Events:
        getAll:
          Type: Api
          Properties:
            Path: /getAll
            Method: GET
  getAllCountries:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/
      Handler: get-all-countries.getAllCountries
      Runtime: nodejs16.x
      Layers:
        - !Ref ApiLayer
      Architectures:
        - x86_64
      Events:
        getAllCountries:
          Type: Api
          Properties:
            Path: /getAllCountries
            Method: GET
  getByCountry:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambdas/
      Handler: get-by-country.getByCountry
      Runtime: nodejs16.x
      Layers:
        - !Ref ApiLayer
      Architectures:
        - x86_64
      Events:
        getByCountry:
          Type: Api
          Properties:
            Path: /getByCountry/{country}
            Method: GET

Outputs:
  WebEndpoint:
    Description: "Covid API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
